Test Project/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Product_Has_Extended_Warranty__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Product Has Extended Warranty</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Purchase_Date__c</fullName>
        <label>Product Purchase Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product_Total_Warranty_Days__c</fullName>
        <label>Product Total Warranty Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

Test Project/src/classes/SecretInfomationTest.cls
@isTest
private class SecretInfomationTest {

    @isTest static void createCase(){
        //Implement Test Code
                Case myCase = new Case();
                myCase.Product_Purchase_Date__c         = Date.today();
                myCase.CreatedDate                      = Date.today();
                myCase.Product_Total_Warranty_Days__c   = 15;
                myCase.Product_Has_Extended_Warranty__c = true;
                myCase.Origin                           = 'Phone';
                myCase.description                      = 'SSN';
        
                insert myCase;

                myCase.description                      =  'Social Security Number'  ;

                update myCase;

                myCase.description                      =   'Passport' ;

                update myCase;

                myCase.description                      =   'Bodyweight' ;

                update myCase;
            }
        

        
        
        /*
        myCase.description                      =  'Social Security Number'  ;

        update myCase;

        myCase.description                      =   'Passport' ;

        update myCase;

        myCase.description                      =   'Bodyweight' ;

        update myCase;
        */
    }